# Network Listeners
listeners:
  # Listen on TCP socket
  mqtt:
    addr: 0.0.0.0:1883
    reuse_port: false

# Authentication
auth:
  enable: false
  anonymous:
    allow: true

# Scram Users (required field)
scram_users: {}
sasl_mechanisms:
- SCRAM-SHA-256


# When client connect with MQTT v3.1 protocol, if set this option to true, server will forbid client identifier length greater than 23.
check_v310_client_id_length: false
# (v5.0 only) The shared subscription mode, can be: [Random, HashClientId, HashTopicName]
shared_subscription_mode: Random
# Maximum allowed QoS the client can publish or subscribe
max_allowed_qos: 2
# Timeout seconds to resend inflight pending messages (unit: second)
inflight_timeout: 15
# Maximum inflight pending messages for client default value
max_inflight_client: 10
# Maximum inflight pending messages the server will handle
max_inflight_server: 10
# Maximum allowed pending messages in memory
max_in_mem_pending_messages: 256
# (unused) Maximum allowed pending messages in database
max_in_db_pending_messages: 65536
# (v5.0 only) The minimum allowed keep alive
min_keep_alive: 10
# (v5.0 only) The maximum allowed keep alive
max_keep_alive: 65535
# (v5.0 only, unused)
multiple_subscription_id_in_publish: true
# (v5.0 only) The maximum session expiry interval value can set in connect packet (unit: second)
max_session_expiry_interval: 4294967295
# (v5.0 only) The maximum packet size given by client (to limit server, unit: byte)
max_packet_size_client: 268435460
# (v5.0 only) The maximum packet size given by server (to limit client, unit: byte)
max_packet_size_server: 268435460
# (v5.0 only) The maximum topic alias value can be used in publish packet
topic_alias_max: 65535
# (v5.0 only) Whether support retained message
retain_available: true
# (v5.0 only) Whether support shared subscription
shared_subscription_available: true
# (v5.0 only) Whether support subscription identifiers
subscription_id_available: true
# (v5.0 only) Whether supports wildcard subscriptions
wildcard_subscription_available: true
# The value indicate whether call certain hook function
hook:
  enable_before_connect: true
  enable_after_connect: true
  enable_publish: true
  enable_subscribe: true
  enable_unsubscribe: true
